name: GitHub Actions Demo

on:
  push: 
    branches: ["main"]
    paths-ignore: [.github/**]
  pull_request:
    branches: ["main"]    
  workflow_dispatch:
  schedule:
    - cron: '15 6 * * 0'

jobs:
  Build:
    runs-on: unbuntu-latest
    steps:
      - run: echo "The job was triggered by a ${{ github.event_name }} event."
      - run: echo "The current branch is ${{ github.ref }}."
